### PR TITLE
chore: modernise tooling and reduce package size

### PR DESCRIPTION
**Pull request by joepegler**
# Summary

1. 70% reduction in bundle size.
2. Tree-shaking
3. Simplified folder structure
4. Replace prettier with biome
5. Replace jest with vitest
6. Replace node with bun
7. Added codecov
8. Added size reporting
9. Automated TSDoc builds
10. Removed Monorepo setup
11. Added changesets for greatly simplified release process
12. Removed aa-core
13. Added “Code of conduct” and “Security”

### CODE REVIEW

**Comment by joepegler** [comment]
Here are the passing e2e tests: https://github.com/bcnmy/biconomy-client-sdk/actions/runs/8704460093/job/23872782014

**Comment by joepegler** [comment]
Corresponding PR in sdk-examples. https://github.com/bcnmy/sdk-examples/pull/40/files, All works nicely

**Comment by VGabriel45** [comment]
Nice job

**Comment by AmanRaj1608** [comment]
Looks great, Why "Replace node with bun" tho
Haven't seen any team working with bun on production

**Comment by joepegler** [comment]
> Looks great, Why "Replace node with bun" tho
> Haven't seen any team working with bun on production

Only because it's faster. viem, permissionless and zerodev all use bun

**Comment by joepegler** [comment]
- https://github.com/wevm/viem/blob/main/bun.lockb
- https://github.com/pimlicolabs/permissionless.js/blob/main/bun.lockb
- https://github.com/zerodevapp/sdk/blob/main/bun.lockb

**Review by AmanRaj1608 — APPROVED** [review]
makes sense approved

**Review by livingrockrises — APPROVED** [review]

**Comment by livingrockrises** [comment]
size report is not getting generated

**Review by VGabriel45 — APPROVED** [review]

**Pull request merged**
