### PR TITLE
fix:some cleanup

### PR DESCRIPTION
**Pull request by mhsnprvr**
* cleaned some duplicate files
* refactored some repeated functionalities
* improved some types
* fixed a potential bug related to types in BiconomySmartAccountV2

Recommendation: While I may not be very familiar with the codebase, I propose the adoption of TypeChain. it can significantly streamline the development process by automatically generating TypeScript typings for Ethereum smart contracts. By doing so, it can alleviate a considerable amount of overhead for developers, ensuring type safety and enhancing productivity.

---

## PR-Codex overview
The focus of this PR is to update file paths, import types, and fix potentially incorrect V values in signatures.

### Detailed summary
- Updated file paths and import types
- Fixed potentially incorrect V values in signatures
- Added `ERC20_ABI` to `ERC20.ts`
- Added `SMART_ACCOUNT_INFO` object to `Constants.ts`
- Updated `getABISVMSessionKeyData` function parameter types

> The following files were skipped due to too many changes: `src/modules/MultichainValidationModule.ts`, `src/paymaster/BiconomyPaymaster.ts`, `src/account/BaseSmartContractAccount.ts`, `src/modules/utils/Helper.ts`, `src/account/BiconomySmartAccountV2.ts`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by joepegler** [comment]
> Recommendation: While I may not be very familiar with the codebase, I propose the adoption of TypeChain. it can significantly streamline the development process by automatically generating TypeScript typings for Ethereum smart contracts. By doing so, it can alleviate a considerable amount of overhead for developers, ensuring type safety and enhancing productivity.
> 

We had Typechain before but it added a lot of bloat. I'm fine with it only if you can add it as a dev dependency

**Review by joepegler — APPROVED** [review]

**Comment by joepegler** [comment]
Conflicts

**Comment by joepegler** [comment]
Do you not have contributor access to our repo yet?

**Review by joepegler — CHANGES_REQUESTED** [review]
Failing tests 🤔

**Comment by mhsnprvr** [comment]
> > Recommendation: While I may not be very familiar with the codebase, I propose the adoption of TypeChain. it can significantly streamline the development process by automatically generating TypeScript typings for Ethereum smart contracts. By doing so, it can alleviate a considerable amount of overhead for developers, ensuring type safety and enhancing productivity.
> 
> We had Typechain before but it added a lot of bloat. I'm fine with it only if you can add it as a dev dependency

sure, I'll add it

**Comment by mhsnprvr** [comment]
> Failing tests 🤔

let me see

**Comment by mhsnprvr** [comment]
> Do you not have contributor access to our repo yet?

nope, asked in a channel, no response

**Comment by mhsnprvr** [comment]
> Failing tests 🤔

isn't it related to env variables?

**Comment by joepegler** [comment]
> > Failing tests 🤔
> 
> isn't it related to env variables?

Other PRs aren't having the same problem, is it because it's a PR from a forked repo? 🤔

**Comment by mhsnprvr** [comment]
> > > Failing tests 🤔
> > 
> > 
> > isn't it related to env variables?
> 
> Other PRs aren't having the same problem, is it because it's a PR from a forked repo? 🤔

it might be, is it possible to test on your machine?

**Comment by mhsnprvr** [comment]
> > Recommendation: While I may not be very familiar with the codebase, I propose the adoption of TypeChain. it can significantly streamline the development process by automatically generating TypeScript typings for Ethereum smart contracts. By doing so, it can alleviate a considerable amount of overhead for developers, ensuring type safety and enhancing productivity.
> 
> We had Typechain before but it added a lot of bloat. I'm fine with it only if you can add it as a dev dependency

  about typechain suggestion, I understood today that alternative approaches are better (since typechain stopped the development), but I saw some errors in types of contracts using it, so maybe it's better if viem usage gets improved

**Pull request closed without merging**
